name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - id: configure
        name: Configure
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo ::set-output name=publish::true
          fi

      - name: Install dependencies
        run: |
          make install

      - name: Test
        run: |
          make test

      - name: Publish
        if: steps.configure.outputs.publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make build
          make publish
